Build: Lock Node.js version to v10 in .nvmrc
Node.js 12 fails on `grunt deploy`, the following error appears during the
`wordpress-deploy` task:

```
>> ReferenceError: primordials is not defined
```

This is because we have the natives module in the dependency tree:

```
$ npm ls natives
api.jquery.com@1.12.39 /Users/mgolebiowski/projects/public/jquery/api.jquery.com
└─┬ grunt-jquery-content@3.0.1
  └─┬ grunt-wordpress@2.1.2
    └─┬ gilded-wordpress@1.0.3
      └─┬ glob@4.0.6
        └─┬ graceful-fs@3.0.12
          └── natives@1.1.6
```

and that module no longer works in Node.js 12. Until this is fixed, lock the
Node.js version in .nvmrc to v10 which is supported until April 2021[1].

Also, commit package-lock.json changes generated with npm 6.9.0 that's included
in Node.js 10.16.3.

[1] https://github.com/nodejs/Release